Fixing queries updates to BreakpointMatchers
vtex-apps/responsive-values pull request #11
Opened 2021-01-06 23:00 UTC by icazevedo

#### What problem is this solving?

This problem solves a very specific bug: when the definition for a responsive value changes to a more complex one with `queries`, say, from:

 ```json
{
    "itemsPerRow": 1
}
```

**to**

 ```jsonc
{
    "itemsPerRow": {
            "(min-width:1300px)": 4, //This is a query
            "desktop": 3,
            "tablet": 3,
            "phone": 2
    }
}
```

the `BreakpointMatchers` variable present on the `useMediaQueryList` hook wouldn't be updated with this change, which caused the hook to try to add a listener to an `undefined` value, thus breaking the component.

This was also caused by the `() => { ... }` present on the `useState` call inside the hook mentioned above, which asserted that the initial value function would only run once (on the first render), preventing the `BreakpointMatchers` variable to be updated. The removal of this behavior was not necessary with this solution, which I think is more speedy.

#### How to test it?

After you load the page, try changing the gallery layout to Grid mode.

[Breaking workspace](https://icarorv--storecomponents.myvtex.com/apparel---accessories/?layout=list)

[Healthy workspace](https://icarosearch--storecomponents.myvtex.com/apparel---accessories/?layout=list)

#### Screenshots or example usage:
Image of the bug
<img width="704" alt="Screen Shot 2021-01-06 at 19 55 34" src="https://user-images.githubusercontent.com/8127610/103828108-2780dc80-5059-11eb-9457-c9fdbf02110a.png">

#### Describe alternatives you've considered, if any.

I considered removing the anonymous function from the `useState` hook, but I was afraid it would hurt performance.

#### Related to / Depends on

Related to [search-result#xxx]()

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/fefZ2NUMZmIjWNokVi/source.gif)

2021-01-06 23:26 UTC, klzns requested changes
Can you create a test for this case?

2021-01-07 15:12 UTC, vitorflg approved these changes
LGTM

2021-01-08 18:46 UTC, igorbrasileiro approved these changes
LGTM

2021-01-12 16:28 UTC, klzns approved these changes

2021-01-14 12:40 UTC, merged