Feat/support media queries
vtex-apps/responsive-values pull request #9
Opened 2020-07-29 16:37 UTC by kaisermann

#### What problem is this solving?

Breaking the chains of only being able to use device-related media queries.

#### How to test it?

Go to: https://potato--storecomponents.myvtex.com/

WIP

#### Screenshots or example usage:

![image](https://user-images.githubusercontent.com/12702016/88827459-5e94bd00-d1a0-11ea-9c97-07866f300647.png)

#### Related to / Depends on

https://vtex-dev.atlassian.net/jira/software/projects/SF/boards/105?selectedIssue=SF-248

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/huUrBp3dvH3fq/giphy.gif)

2020-07-29 16:53 UTC, klzns approved these changes
It looks great.

I miss some tests though 💔

2020-07-31 17:27 UTC, klzns approved these changes

2020-07-31 17:27 UTC, klzns commented on react/tests/useResponsiveValue.test.tsx
> +  devices.forEach((device) => {
Maybe use test.each instead?
https://jestjs.io/docs/en/api#testeachtablename-fn-timeout

2020-07-31 17:29 UTC, klzns requested changes
Build is failing

Maybe remove tests from going to IO
![image](https://user-images.githubusercontent.com/284515/89060897-2de88b00-d33a-11ea-872b-326995423df6.png)

2020-07-31 17:34 UTC, victorhmp requested changes

2020-07-31 17:34 UTC, victorhmp commented on react/hooks/useMediaQueryList.ts
> +      let mql = BreakpointMatchers[query]
Avoid abbreviations to make this bit of code more readable :)

2020-07-31 17:34 UTC, victorhmp commented on react/hooks/useMediaQueryList.ts
> +      const mql = BreakpointMatchers[query]
Same thing here

2020-07-31 18:18 UTC, victorhmp approved these changes

2020-07-31 18:51 UTC, lbebber approved these changes
LGTM (left a couple of suggestions over DM but this looks good as it is)

2020-07-31 18:51 UTC, lbebber commented on react/hooks/useMediaQueryList.ts
> +        // ugly side-effect（＞д＜）
```suggestion
```

no need to be apologetic (explain why it was done as a side effect if needed)

2020-07-31 18:51 UTC, lbebber commented on react/hooks/useMediaQueryList.ts
> +        // ugly side-effect to get a up-to-date initial value（＞д＜）
no need to be apologetic here, it makes sense

2020-07-31 19:24 UTC, klzns approved these changes

2020-08-03 13:38 UTC, merged

2020-08-03 14:19 UTC, carolinamenezes commented on docs/README.md
> +Utility for using props that accept different values for different devices or media queries.
```suggestion
In VTEX IO, some component's props, such as the ones from the [Flex-Layout](https://developers.vtex.com/docs/vtex-flex-layout) app, support responsive-values. That means it's possible to assign, to the same prop, different values for each device type or specific media queries.

Props that support responsive values accept either a unique value for all cases or an object containing specific definitions for each of the following: `phone`, `tablet`, `desktop`, `mobile` (for both phone and tablet), and media queries.
```

2020-08-03 14:19 UTC, carolinamenezes commented on docs/README.md
> +...or different values depending on the device or a media query:
```suggestion
... or different values depending on the device type or specific media queries:
```

2020-08-03 14:19 UTC, carolinamenezes commented on docs/README.md
> +- The definiton order matters. If more than one media query is matched, the first matched one is used.
```suggestion
Considering the use of a device, which responsive values are missing, the page style will match the following largest screen size definition.

For example, if a component has only `phone` and `desktop` responsive values defined, tablet devices will receive the value from `desktop`. 

Media queries, in turn, have no fallback behavior. Hence, when using this feature, it's important to keep in mind that:

- Media queries take precedence over devices. Therefore, if a media query matches the current state of a window, all device definitions are ignored.
- The order definition matters. Therefore, if more than one media query matches the current state of a window, the first match is used.
- Media queries are written following the [standard media query syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#Syntax).
```

2020-08-03 14:19 UTC, carolinamenezes commented on docs/README.md
```suggestion
```

2020-08-03 14:19 UTC, carolinamenezes commented on docs/README.md
```suggestion
```